修改地图翻译: ze_diddle_v3
fys-csgo/servers-config pull request #1852
Opened 2022-11-02 03:38 UTC by Airnoins

## 该PR作用的地图是(仅英文小写)
ze_diddle_v3
## 为什么要增加/修改这个东西
翻译修正
## 在提交PR前请确认已完成以下工作
- 我已经阅读了``OP手册`` 和 ``参数修改公约``.
- 我已经遵守了手册和公约的指导.
- 我已经自检过以确认没有错误的符号拼写和非法字符.
- 我已经按照公约的要求正确填写PR的标题.
- 我在提交PR前已将分支更新到最新.
- 我确认该PR中仅包含一张地图的内容.

2022-11-08 22:52 UTC, LunarEclipse1026 commented
修改倒计时的地方直接把多余提示关闭，不要修改成中文。

2022-11-11 10:21 UTC, Kxnrl requested changes

2022-11-11 10:21 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/mapstage.kv
> +        "stages"  "12"
?

2022-11-11 10:22 UTC, Kxnrl commented
> 为什么要增加/修改这个东西
修改神器模式及cd

这是问你为什么要改, 不是他妈的问你你做了什么

2022-11-12 10:38 UTC, closed without merging