BOSSHP
fys-csgo/servers-config pull request #216
Opened 2020-09-13 17:15 UTC by FYSxiaosan

2020-09-14 03:28 UTC, Kxnrl requested changes

2020-09-14 03:28 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/bosshp/ze_sky_fantasy_v1_4.cfg
> +            "displayname"  "核心<蓝>"
这个属不属于multiparts?

2020-10-19 05:50 UTC, LunarEclipse1026 approved these changes

2020-10-19 05:51 UTC, LunarEclipse1026 approved these changes

2020-10-19 05:55 UTC, LunarEclipse1026 submitted a review, later dismissed

2020-10-29 12:32 UTC, Kxnrl approved these changes

2020-10-29 12:32 UTC, merged