修改地图参数: ze_castle_of_the_bladekeeper_v1
fys-csgo/servers-config pull request #2274
Opened 2023-04-08 13:23 UTC by trysn

## 该PR作用的地图是(仅英文小写)
ze_castle_of_the_bladekeeper_v1
## 为什么要增加/修改这个东西
修改一关制参数，68分钟，14个僵尸全点速度守不住
## 在提交PR前请确认已完成以下工作
- 我已经阅读了``OP手册`` 和 ``参数修改公约``.
- 我已经遵守了手册和公约的指导.
- 我已经自检过以确认没有错误的符号拼写和非法字符.
- 我已经按照公约的要求正确填写PR的标题.
- 我在提交PR前已将分支更新到最新.
- 我确认该PR中仅包含一张地图的内容.

2023-04-09 07:51 UTC, Kxnrl requested changes

2023-04-09 07:51 UTC, Kxnrl commented on ZombiEscape/cfg/sourcemod/map-configs/_extreme_bladekeeper.cfg
> +zr_classes_csgo_knockback_airmultiplier "1.0"
value out-of-bound

2023-04-10 14:29 UTC, SeaSedgeht approved these changes

2023-04-11 11:37 UTC, Kxnrl approved these changes

2023-04-11 11:37 UTC, merged