更新undertale_sans地图版本更新参数
fys-csgo/servers-config pull request #295
Opened 2020-11-10 13:20 UTC by SeaSedgeht

2020-11-10 13:56 UTC, Kxnrl requested changes

2020-11-10 13:56 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/mapdata.kv
> +		"m_Description"		"*咸鱼* 传说之下：sans战"
任何地图的包场都不能低于最低阈值

2020-11-10 14:30 UTC, Kxnrl requested changes

2020-11-10 14:30 UTC, Kxnrl commented on ZombiEscape/cfg/sourcemod/map-configs/ze_undertale_sans_final.cfg
> +ze_credits_pass_round "8"
8 credits?

2020-11-11 04:47 UTC, SeaSedgeht commented on ZombiEscape/cfg/sourcemod/map-configs/ze_undertale_sans_final.cfg
> +ze_credits_pass_round "8"
已修改

2020-11-11 04:47 UTC, SeaSedgeht commented on ZombiEscape/addons/sourcemod/configs/mapdata.kv
> +		"m_Description"		"*咸鱼* 传说之下：sans战"
已作出修改

2020-11-11 12:57 UTC, Kxnrl approved these changes

2020-11-11 13:20 UTC, merged