补全生化奇兵v71bosshp
fys-csgo/servers-config pull request #496
Opened 2021-02-12 11:44 UTC by vwy666v

2021-02-12 11:59 UTC, Kxnrl requested changes

2021-02-12 11:59 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/bosshp/ze_bioshock_v7_1_csgo_a2.cfg
> +            "displayname" "科恩·ruby"
invalid symbol '科恩·ruby' in '1'

2021-02-12 12:08 UTC, vwy666v commented on ZombiEscape/addons/sourcemod/configs/bosshp/ze_bioshock_v7_1_csgo_a2.cfg
> +            "displayname" "科恩·ruby"
its ok i fix 3q

2021-02-15 17:04 UTC, Kxnrl approved these changes

2021-02-15 17:04 UTC, merged