面条人翻译
fys-csgo/servers-config pull request #639
Opened 2021-04-17 12:32 UTC by LENXINXIN

2021-04-19 12:20 UTC, SeaSedgeht commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_slender_escape_rc2.txt
>  	}
非倒计时不要写成阿拉伯数字形式

2021-04-21 12:00 UTC, Kxnrl requested changes

2021-04-21 12:00 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_slender_escape_rc2.txt
> +		"chi"		"**[故事] 我们在监狱碰到1个叫面条人的好人 - 他想帮我们从这个监狱逃出去! **"
this is comment

2021-04-21 12:07 UTC, SeaSedgeht commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_slender_escape_rc2.txt
>  	}
了解

2021-05-31 00:46 UTC, closed without merging