天空竞技场翻译补全
fys-csgo/servers-config pull request #675
Opened 2021-04-30 10:00 UTC by 1024TzKi

修改之前补充翻译中的错误标点

2021-05-02 23:00 UTC, Kxnrl requested changes

2021-05-02 23:00 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_sky_athletic_adv_v9_10.txt
> +		"chi"		"**章节已损坏,去...另外..路..**"
??

2021-05-02 23:55 UTC, 1024TzKi commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_sky_athletic_adv_v9_10.txt
> +		"chi"		"**章节已损坏,去...另外..路..**"
az，只是仿照上面的格式写的a
character broken and "find" another way out
差不多这样

2021-05-02 23:59 UTC, 1024TzKi commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_sky_athletic_adv_v9_10.txt
> +		"chi"		"**章节已损坏,去...另外..路..**"
az，nmd懂了，我sb了

2021-05-06 12:38 UTC, Kxnrl approved these changes

2021-05-06 12:38 UTC, merged