misc update
fys-csgo/servers-config pull request #680
Opened 2021-05-02 09:18 UTC by YuricaKirisame

2021-05-02 22:58 UTC, Kxnrl requested changes

2021-05-02 22:58 UTC, Kxnrl commented on MiniGames/cfg/sourcemod/map-configs/mg_warmcup_headshot.cfg
> +sv_gravity "1200"
?

2021-05-05 12:19 UTC, YuricaKirisame commented on MiniGames/cfg/sourcemod/map-configs/mg_warmcup_headshot.cfg
> +sv_gravity "1200"
?

2021-05-05 13:14 UTC, Kxnrl commented on MiniGames/cfg/sourcemod/map-configs/mg_warmcup_headshot.cfg
> +sv_gravity "1200"
??

2021-05-06 12:57 UTC, Kxnrl approved these changes

2021-05-06 12:57 UTC, merged