增加地图翻译-小米纳斯
fys-csgo/servers-config pull request #694
Opened 2021-05-08 10:38 UTC by 1024TzKi

增加地图翻译

2021-05-17 20:26 UTC, Kxnrl requested changes

2021-05-17 20:26 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_LOTR_Minas_Tiret_p2.txt
> +        "chi" "**一**"
??

2021-05-17 22:40 UTC, 1024TzKi commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_LOTR_Minas_Tiret_p2.txt
> +        "chi" "**一**"
emmm单机跑不太清楚服务器倒计时提示开着的效果，所以只留了下面的最下面的5s倒计时。
一下如果是跳刀仓库红刀那种格式还是全删了吧

2021-05-18 12:34 UTC, Kxnrl requested changes
你读了5秒, 那后面的4321应该block掉

2021-05-18 13:23 UTC, 1024TzKi commented
> 你读了5秒, 那后面的4321应该block掉

之前在其他文件大概只见到过"command"的应用，照着同格式改了一下

2021-05-18 16:04 UTC, Kxnrl requested changes

2021-05-18 16:04 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_LOTR_Minas_Tiret_p2.txt
> +        "blocked"
```
"blocked" "1"
```

2021-05-18 21:36 UTC, Kxnrl requested changes

2021-05-18 21:36 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_LOTR_Minas_Tiret_p2.txt
> +        "blocked" "**1 seconds**"
```
"blocked" "1"
```
不是复制内容啊..

2021-05-19 08:26 UTC, Kxnrl requested changes

2021-05-19 08:26 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_LOTR_Minas_Tiret_p2.txt
> +        "blocked" "4"
```
"blocked" "1"
```
这个参数只有一个值, 就是`1`

2021-05-19 10:33 UTC, 1024TzKi commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_LOTR_Minas_Tiret_p2.txt
> +        "blocked" "4"
> ```
> "blocked" "1"
> ```
> 
> 这个参数只有一个值, 就是`1`

顺便问一下countdown的使用，大概是这样 “countdown” “25”吗？

2021-05-19 14:10 UTC, Kxnrl approved these changes

2021-05-19 14:41 UTC, merged