增加地图翻译-血战画廊
fys-csgo/servers-config pull request #697
Opened 2021-05-10 00:59 UTC by 1024TzKi

主要增加stage 2翻译

2021-05-17 20:25 UTC, Kxnrl requested changes

2021-05-17 20:25 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_bloodstrike_escape_v2.txt
> +		"chi"		"**章节 2**"
一般不用阿拉伯数字

2021-05-17 20:25 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_bloodstrike_escape_v2.txt
> +		"chi"		"章节 2 完成"
~

2021-05-18 09:12 UTC, 1024TzKi commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_bloodstrike_escape_v2.txt
> +		"chi"		"**章节 2**"
这个我是看上面stage1是这样写的，已经把stage1和2的都改了

2021-05-18 09:12 UTC, 1024TzKi commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_bloodstrike_escape_v2.txt
> +		"chi"		"章节 2 完成"
~

2021-05-18 21:37 UTC, Kxnrl approved these changes

2021-05-19 08:35 UTC, merged