增加新图配置
fys-csgo/servers-config pull request #699
Opened 2021-05-15 14:38 UTC by HaiTaiPR

增加新图核电站V2_3_gg地图配置

2021-05-15 15:08 UTC, SeaSedgeht approved these changes

2021-05-16 11:38 UTC, Kxnrl requested changes
能不能别瞎鸡巴写

2021-05-16 11:38 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/bosshp/ze_Stalker_Ultimate_v2_3_gg.cfg
> +            "hitbox"        "boss_break"
？？

2021-05-17 20:24 UTC, Kxnrl commented
先把翻译盖好吧

2021-05-18 07:15 UTC, LunarEclipse1026 approved these changes

2021-05-18 12:39 UTC, closed without merging