狮子王里世界添加倒计时
fys-csgo/servers-config pull request #721
Opened 2021-05-24 09:31 UTC by 1024TzKi

为狮子王里世界贴门触发添加独立倒计时，方便指挥计算并安排撤退
屏蔽部分重复倒计时

2021-05-24 14:26 UTC, Kxnrl requested changes

2021-05-24 14:26 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_santassination_v3.txt
> +		"chi"		"**灼眼尊者玩任天堂64**"
这会触发倒计时

2021-05-24 14:26 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_santassination_v3.txt
> +		"countdown" 40
这种倒计时, 是不会被覆盖的, 所以开启了就会触发. 而且你引号呢?

2021-05-24 17:47 UTC, SYhin commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_santassination_v3.txt
> +		"countdown" 40
"countdown" "xx"这样写过不了审查啊

2021-05-24 22:29 UTC, 1024TzKi commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_santassination_v3.txt
> +		"countdown" 40
> 这种倒计时, 是不会被覆盖的, 所以开启了就会触发. 而且你引号呢?

加引号的话过不了bulid check，不知道为什么。

2021-05-24 22:29 UTC, 1024TzKi commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_santassination_v3.txt
> +		"chi"		"**灼眼尊者玩任天堂64**"
ok

2021-05-25 00:46 UTC, Kxnrl commented
而且主要是, 你里世界开的倒计时, 如果出现两个一样的数字, 它是会直接显示两个的. 不会跟翻译文本一样自动合并.
比如你前面40, 之后, 过了20秒再出一个20, 那就是显示2个20. 明白了不

2021-05-25 00:47 UTC, Kxnrl requested changes

2021-05-25 00:47 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_santassination_v3.txt
> +		"countdown" 40
现在可以的吧

2021-05-25 22:10 UTC, 1024TzKi commented
> 而且主要是, 你里世界开的倒计时, 如果出现两个一样的数字, 它是会直接显示两个的. 不会跟翻译文本一样自动合并.
> 比如你前面40, 之后, 过了20秒再出一个20, 那就是显示2个20. 明白了不
调了一下其中不是很关键的倒计时，这下是没有一样的倒计时

2021-05-31 00:46 UTC, closed without merging