艾辛格翻译更新&地图配置更改
fys-csgo/servers-config pull request #745
Opened 2021-06-03 10:11 UTC by 1024TzKi

更新并补充部分翻译；
配置部分:
1.削减坠落伤害；
主要针对Stage2断后撤退中的大量下楼梯损血，以及Stage3最后低重力上天台失误后直接摔死。考虑到传送至boss后均会恢复至满血，故在目前无血针的情况下通过削减坠落伤害来防止在路途中大量掉人。

2.神器云点限制提升：
主要针对Stage2的树人技能对僵尸的击退效果及其明显，甚至导致僵尸撞至地形边缘大飞导致团灭。需要玩家间配合并听从指挥。实战中已多次出现树人反向击退僵尸导致炸团。建议提高云点限制。

3.初始火瓶增加：
主要针对Stage1中击败蜘蛛到下一个守点路线过长人类断后无法有效减速僵尸、Stage2流程较短且只有一瓶火的情况下断后压力较大、Stage3在人类神器甘道夫技能空窗期或操作失误的情况下非常依赖火瓶。故建议增加初始火瓶。

2021-06-05 19:29 UTC, Kxnrl commented
这个图我不太清楚, 但是说如果是必摔的点可以考虑用stripper动态调整, 如果是可以走位避免的, 那就没有修改的必要..
云点调整是可以的.
火瓶如果需要增加, 也应该是优先考虑购买上限, 不是初始火瓶.

2021-06-06 09:47 UTC, 1024TzKi commented on ZombiEscape/cfg/sourcemod/map-configs/ze_lotr_isengard_csgo1.cfg
> +sv_falldamage_scale "0.6"
> see comment before

get

2021-06-06 11:03 UTC, 1024TzKi commented
> 这个图我不太清楚, 但是说如果是必摔的点可以考虑用stripper动态调整, 如果是可以走位避免的, 那就没有修改的必要..
> 云点调整是可以的.
> 火瓶如果需要增加, 也应该是优先考虑购买上限, 不是初始火瓶.

可否使用consolet的command输出，类似西子王序章云点那样

2021-06-07 00:23 UTC, Kxnrl commented
可以是可以, 但是翻译文件的时机不可能跟stripper一样细致的哦.
有文本就还好, 没有文本就比较麻烦

2021-06-07 07:51 UTC, 1024TzKi commented
> 可以是可以, 但是翻译文件的时机不可能跟stripper一样细致的哦.
> 有文本就还好, 没有文本就比较麻烦

先用command改了stage3影响最大的地方。stage2的部分先不动我先去学学

2021-06-09 00:14 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_lotr_isengard_csgo1.txt
>           //L2,L3电梯倒计时
//内容会导致kv解析错误
//要跟空格
我也不知道为什么V社会这样设计

2021-06-09 00:15 UTC, Kxnrl requested changes

2021-06-09 00:15 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_lotr_isengard_csgo1.txt
>           //L2,L3电梯倒计时
//内容会导致kv解析错误
//要跟空格
我也不知道为什么V社会这样设计

2021-06-09 05:13 UTC, 1024TzKi commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_lotr_isengard_csgo1.txt
>           //L2,L3电梯倒计时
az我也在奇怪西子王那个改云点为什么最后只加了个空格来着

2021-06-09 23:43 UTC, Kxnrl approved these changes

2021-06-09 23:51 UTC, merged