大黑魂限制awp数量，删除血针
fys-csgo/servers-config pull request #749
Opened 2021-06-05 02:28 UTC by c0CoC0c

地图有奶神器
awp5把削减至2把

2021-06-05 19:30 UTC, Kxnrl requested changes

2021-06-05 19:30 UTC, Kxnrl commented on ZombiEscape/cfg/sourcemod/map-configs/ze_dark_souls_ptd_v0_4_csgo7.cfg
> +ze_weapons_awp_counts "2"
why

2021-06-05 23:32 UTC, c0CoC0c commented on ZombiEscape/cfg/sourcemod/map-configs/ze_dark_souls_ptd_v0_4_csgo7.cfg
> +ze_weapons_awp_counts "2"
zm神器被过于针对(地图只有两个zm)

2021-06-09 01:04 UTC, Kxnrl approved these changes

2021-06-09 01:09 UTC, merged