N64恶魔城参数平衡
fys-csgo/servers-config pull request #756
Opened 2021-06-07 11:59 UTC by a1005101871

经过开荒发现闪灵过于强悍,故稍微平衡一下双方参数

2021-06-09 00:15 UTC, Kxnrl requested changes

2021-06-09 00:15 UTC, Kxnrl commented on ZombiEscape/cfg/sourcemod/map-configs/ze_castlevania_64_v1_3_b9_go.cfg
?

2021-06-12 10:26 UTC, a1005101871 commented on ZombiEscape/cfg/sourcemod/map-configs/ze_castlevania_64_v1_3_b9_go.cfg
改回去1秒了

2021-06-13 07:51 UTC, Kxnrl requested changes

2021-06-13 07:51 UTC, Kxnrl commented on ZombiEscape/cfg/sourcemod/map-configs/ze_castlevania_64_v1_3_b9_go.cfg
> +ze_weapons_spawn_molotov "1"
这个图有必要开局又冰又火的吗

2021-06-13 07:53 UTC, a1005101871 commented on ZombiEscape/cfg/sourcemod/map-configs/ze_castlevania_64_v1_3_b9_go.cfg
> +ze_weapons_spawn_molotov "1"
已经吧冰删除了

2021-06-13 07:53 UTC, Kxnrl approved these changes

2021-06-13 08:34 UTC, merged