entwatch神器名称修改
fys-csgo/servers-config pull request #767
Opened 2021-06-15 17:01 UTC by vwy666v

如题

2021-06-20 09:29 UTC, Kxnrl requested changes

2021-06-20 09:29 UTC, Kxnrl commented on ZombiEscape/cfg/sourcemod/map-entwatch/ze_raintime1_torontoisland_v5nor.cfg
> -        "shortname"         "环形风"
为什么不写旋风

2021-06-20 09:29 UTC, Kxnrl commented on ZombiEscape/cfg/sourcemod/map-entwatch/ze_raintime2_stormwindkeep_v2.cfg
> -    "shortname"         "炽翎上仙"
不是符华吗

2021-06-21 15:54 UTC, Kxnrl commented on ZombiEscape/cfg/sourcemod/map-entwatch/ze_raintime2_stormwindkeep_v2.cfg
> -    "shortname"         "炽翎上仙"
这里好像字数太多显示不了哦

2021-06-23 03:17 UTC, vwy666v commented on ZombiEscape/cfg/sourcemod/map-entwatch/ze_raintime2_stormwindkeep_v2.cfg
> -    "shortname"         "炽翎上仙"
ok

2021-06-23 03:17 UTC, vwy666v commented on ZombiEscape/cfg/sourcemod/map-entwatch/ze_raintime1_torontoisland_v5nor.cfg
> -        "shortname"         "环形风"
ok

2021-06-23 14:40 UTC, merged