增加最后跳刀击退以及修改部分翻译
fys-csgo/servers-config pull request #779
Opened 2021-06-21 16:24 UTC by a1005101871

最后平台跳刀增加击退,防止僵尸飞上平台.

2021-06-21 18:49 UTC, Kxnrl requested changes

2021-06-21 18:49 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_uchiha_legacy_v1_3f_cm1.txt
> +        "command" "zr_knockback_multi "3.0"
?

2021-06-21 18:49 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_uchiha_legacy_v1_3f_cm1.txt
> +        "command" "zr_knockback_multi "3.0"
会不会抄作业啊

2021-06-22 10:01 UTC, a1005101871 commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_uchiha_legacy_v1_3f_cm1.txt
> +        "command" "zr_knockback_multi "3.0"
好了这次属实没问题

2021-06-23 14:44 UTC, Kxnrl approved these changes

2021-06-23 15:03 UTC, merged