update stripper.
fys-csgo/servers-config pull request #797
Opened 2021-07-05 18:35 UTC by YuricaKirisame

2021-07-06 06:56 UTC, Kxnrl requested changes

2021-07-06 06:56 UTC, Kxnrl commented on MiniGames/addons/stripper/maps/mg_cbmultigames_alphabox_v10.cfg
> -;-------------------------------------------------------------------------------
这图是删了么

2021-07-06 06:56 UTC, Kxnrl commented on MiniGames/addons/stripper/maps/mg_thc_lego_multimap_go_v4_nc2.cfg
> +// penis
just rainbow 也要修

2021-07-06 14:48 UTC, YuricaKirisame commented on MiniGames/addons/stripper/maps/mg_cbmultigames_alphabox_v10.cfg
> -;-------------------------------------------------------------------------------
是

2021-07-08 07:30 UTC, Kxnrl approved these changes

2021-07-08 12:28 UTC, Kxnrl approved these changes

2021-07-08 12:31 UTC, merged