老图配置查漏补缺加平衡
fys-csgo/servers-config pull request #816
Opened 2021-07-11 22:09 UTC by vwy666v

如题 详见下面文件

2021-07-12 07:50 UTC, Kxnrl requested changes

2021-07-12 07:50 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_hsc_a4_q3.txt
> +        "command" "sm_boomer_enabled 1"
key is unique

2021-07-12 07:50 UTC, Kxnrl commented on ZombiEscape/addons/sourcemod/configs/bosshp/ze_hsc_a4_q3.cfg
> +			"displayname" "夕阳"
??

2021-07-13 03:49 UTC, vwy666v commented on ZombiEscape/addons/sourcemod/configs/console_t/ze_hsc_a4_q3.txt
> +        "command" "sm_boomer_enabled 1"
ok

2021-07-13 03:49 UTC, vwy666v commented on ZombiEscape/addons/sourcemod/configs/bosshp/ze_hsc_a4_q3.cfg
> +			"displayname" "夕阳"
...

2021-07-13 12:33 UTC, Kxnrl approved these changes

2021-07-13 12:33 UTC, merged